accounts/urls.py
from . import views
from django.urls import path


app_name = 'accounts'


urlpatterns = [
    path('signups/', views.profile_register, name="signup"),
    path('login/', views.profile_login, name="login"),
    path('logout/', views.profile_logout, name="account_logout"),
    path('profile/', views.profile_view, name="user-profile"),
    path('profile/delete-account', views.profile_delete, name="delete"),
]

glassfish/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('', include('main.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('reviews.urls')),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='main'),
    path('gallery/', views.gallery, name='gallery'),
    path('visit/', views.visit, name='visit'),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'

urlpatterns = [
    path('reviews/', views.review_display, name='review-display'),
    path('reviews/<slug:slug>/', views.review_detail, name='reviews-detail'),
    path('create/', views.review_create, name='create'),
    path('<slug>/update/', views.review_update, name='update-review'),
    path('<slug>/delete/', views.review_delete, name='delete-review')
]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

STATUS = ((0, "Draft"), (1, "Posted"))


class ReviewPost(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    author = models.ForeignKey(User, null=False, blank=False,
                               on_delete=models.CASCADE,
                               related_name="review_post")
    content = models.TextField(max_length=10000)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)
    featured_image = CloudinaryField('image', default="https://res.cloudinary.com/dgz5gpe5z/image/upload/v1708453621/owy10e5dfvswqrozcc1m.png")

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('ReviewPostDisplay')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ReviewPost, self).save(*args, **kwargs)

reviews/forms.py
from django import forms
from .models import ReviewPost


class CreatePost(forms.ModelForm):
    class Meta:
        model = ReviewPost
        exclude = ('slug', 'author', 'status',)


class EditPost(forms.ModelForm):
    """
    This is the Form to update the Users account
    """
    class Meta:
        model = ReviewPost
        exclude = ('slug', 'author', 'status',)

reviews/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .models import ReviewPost
from django.views.generic import DeleteView
from .forms import EditPost, CreatePost
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from accounts.models import Profile


def review_display(request):
    template_name = "reviews/reviews.html"
    reviews_all = ReviewPost.objects.all()
    context = {
        'reviews_all': reviews_all
    }
    return render(request, template_name, context)


def review_detail(request, slug):
    review = get_object_or_404(ReviewPost, slug=slug)
    template_name = "reviews/reviews_details.html"
    context = {
        'review': review
    }
    return render(request, template_name, context)


@login_required(login_url="/accounts/login/")
def review_create(request):
    """
    A view to create the reviews
    """
    form = CreatePost()
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = CreatePost(request.POST, request.FILES)
        if form.is_valid():
            new_review = form.save(commit=False)
            print(request.user)
            # print(new_review)
            # print(new_review.author)
            new_review.author = request.user
            print(new_review)
            new_review.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Your review has been uploaded!')
            return redirect(reverse('reviews:review-display'))
        else:
            messages.add_message(request, messages.WARNING,
                                 'Somethings gone wrong please try again!')
            return
    template_name = "reviews/create_review.html"
    return render(request, template_name, context)


@login_required(login_url="/accounts/login/")
def review_update(request, slug):
    """
    update
    """
    review = get_object_or_404(ReviewPost, slug=slug)
    if not request.user == review.author:
        messages.warning(request, 'Sorry not Owner of the post!')
        return redirect('reviews:review-display')
    review_form = EditPost(instance=review)
    if request.method == 'POST':
        review_form = EditPost(request.POST,
                               request.FILES,
                               instance=review)
        if review_form.is_valid():
            try:
                review_form.save()
                messages.add_message(request, messages.SUCCESS,
                                     'The review has been successfully')
                return redirect('reviews:review-display')
            except Exception:
                messages.add_message(request, messages.WARNING,
                                     'is it all filled out correctly?')
                context = {
                    'form': review_form
                }
                return render(request,
                              'reviews/update_review.html', context)
    context = {
        'form': review_form
    }
    return render(request, 'reviews/update_review.html', context)


@login_required(login_url="/accounts/login/")
def review_delete(request, slug):
    review = get_object_or_404(ReviewPost, slug=slug)
    if not (request.user == review.author or request.user.is_superuser):
        messages.add_message(request, messages.WARNING,
                             'Somethings gone wrong please try again!')
        return redirect('reviews:review-display')
    review.delete()
    messages.add_message(request, messages.SUCCESS, 'Review Deleted!')
    return redirect('reviews:review-display')

reviews/templates/reviews/create_review.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="height-controller">
<div class="form-container">
    <strong class="add-review">Add Review!</strong>
    <form method="POST" class="create-form form mb-1"
        action="{% if review %}{% url 'reviews:update-review' review.slug %}{% else %}{% url 'reviews:create' %}{% endif %}"
        enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <div class="text-right">
            <a class="back-button" href="{% url 'reviews:review-display' %}">Cancel</a>
            <button type="submit" class="update-button">{% if review %}Save Changes{% else %}Add Review{% endif %}</button>
        </div>
    </form>
</div>
</div>
{% endblock %}

reviews/templates/reviews/reviews.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1 class="review-page-title">Glass Fish Reviews</h1>
<div>
    {% if user.is_authenticated %}
    <div class="review-page-buttons">
        <div>
            <a class="back-button" href="{% url 'reviews:create' %}">Create a Review!</a>
        </div>
        {% else %}
        <div>
            <a class="back-button" href="{% url 'accounts:signup' %}">Join The Site and Post a Review!</a>
        </div>
    </div>
    {% endif %}
</div>
<!-- this is a loop through all reviews -->
<div class="photos-container">
    {% for reviews in reviews_all %}
    <a href="{% url 'reviews:reviews-detail' reviews.slug %}">
        <div class="card-container">
            <div class="card review-card" style="width: 18rem;">
                <div>
                    <div class="review">
                        <div class="review-images">
                            {% if "default" in ReviewPost.featured_image.url %}
                            <img class="card-img-top" src="{{ reviews.featured_image.url }}" alt="placeholder image">
                            {% else %}
                            <img class="card-img-top" src=" {{ reviews.featured_image.url }}" alt="{{ reviews.title }}">
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title review-title capitalize">{{ reviews.title }}</h5>
                            <!-- the "safe" tag prevents the code tags from displaying  -->
                            <div class="reviews-text-container">
                                <p class="card-text capitalize review-body">
                                    {{ reviews.content|truncatechars:100 | safe }}
                                </p>
                                <p class="card-text capitalize">
                                    By- {{ reviews.author }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
<div class="review-page-buttons">
    <a class="back-button" href="{% url 'main:main' %}">Back!</a>
</div>
<!-- closing the loop ^ -->
{% endblock %}

reviews/templates/reviews/reviews_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- rerun through validator when images arfe  sorted -->
<div class="height-controller">
    <div class="form-container">
        <div>
            <img class="card-img-top review-detail-image" src="{{ review.featured_image.url }}" alt="{{ reviews.title }}">        
        </div>
        <div class="review-content">
            <h5 class="review-title capitalize">{{ review.title }}</h5>
            <p class="card-text capitalize review-body">{{ review.content|truncatechars:100 | safe}}</p>
            <p class="card-text capitalize">By {{ review.author }}</p>
        </div>
        {% if user == review.author or user.is_superuser %}
        <div class="admin-buttons">
            <a class="update-button" href="{% url 'reviews:update-review' review.slug %}">Update</a>
            <a class="delete-button" href="{% url 'reviews:delete-review' review.slug %}">Delete</a>
        </div>
        {% endif %}
        <div>
            <a class="back-button" href="{% url 'reviews:review-display' %}">Back!</a>
        </div>
    </div>
</div>
{% endblock %}

reviews/templates/reviews/update_review.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}
{% block content %}
<div class="height-controller">
    <div class="form-container">
        <strong class="add-review">Update Review</strong>
        <form class="create-form" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="update-button">
        </form>
    </div>
</div>
{% endblock %}