accounts/urls.py
from . import views
from django.urls import path


app_name = 'accounts'


urlpatterns = [
    path('signups/', views.profile_register, name="signup"),
    path('login/', views.profile_login, name="login"),
    path('logout/', views.profile_logout, name="account_logout"),
    path('profile/', views.profile_view, name="user-profile"),
    path('profile/delete-account', views.profile_delete, name="delete"),
]

glassfish/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('', include('main.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('reviews.urls')),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='main'),
    path('gallery/', views.gallery, name='gallery'),
    path('visit/', views.visit, name='visit'),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'

urlpatterns = [
    path('reviews/', views.review_display, name='review-display'),
    path('reviews/<slug:slug>/', views.review_detail, name='reviews-detail'),
    path('create/', views.review_create, name='create'),
    path('<slug>/update/', views.review_update, name='update-review'),
    path('<slug>/delete/', views.review_delete, name='delete-review')
]

accounts/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    """
    Main Model for the users profile
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = CloudinaryField('image', default="https://res.cloudinary.com/dgz5gpe5z/image/upload/v1708453621/owy10e5dfvswqrozcc1m.png")

    def __str__(self):
        return f'{self.user.username}'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    """
    This is the Form to create the Users account
    """
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class AccountUpdateForm(forms.ModelForm):
    """
    This is the Form to update the Users account
    """
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileFormUpdate(forms.ModelForm):
    """
    This is the Form to update the Users profile
    """
    class Meta:
        model = Profile
        fields = ['profile_image']
        exclude = ('profile_image.url',)
        


class DeleteUserForm(forms.ModelForm):
    """
    This is the Delete to create the Users account
    """
    class Meta:
        model = User
        fields = []

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import (UserRegisterForm,
                    AccountUpdateForm,
                    ProfileFormUpdate,
                    DeleteUserForm
                    )


def profile_register(request):
    """
    This enables people to create an account if they do not already have one
    """
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Account created!')
            return redirect('accounts:login')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/signup.html', {'form': form})


# Creates the login_view


def profile_login(request):
    """
    This enables people to log in to their account
    """
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                messages.add_message(request, messages.SUCCESS,
                                     'You have been logged in!')
                return redirect('main:main')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login-form.html',
                  {'form': form})


# Creates the log out view

@login_required(login_url="/accounts/login/")
def profile_logout(request):
    """
    profile_logout enables the user to logout
    """
    if request.method == 'POST':
        logout(request)
        messages.add_message(request, messages.SUCCESS,
                             'You have been logged out!')
        return redirect('main:main')
    form = AuthenticationForm()
    return render(request, 'accounts/log-out.html', {'form': form})


@login_required(login_url="/accounts/login/")
def profile_view(request):
    """
    This shows the users their own profile
    if they have one and they are logged into it
    """
    profile_form = ProfileFormUpdate(instance=request.user.profile)
    account_form = AccountUpdateForm(instance=request.user)
    if request.method == 'POST':
        account_form = AccountUpdateForm(request.POST,
                                         instance=request.user)
        profile_form = ProfileFormUpdate(request.POST,
                                         request.FILES,
                                         instance=request.user.profile)
        if account_form.is_valid() and profile_form.is_valid():
            try:
                profile_form.save()
                account_form.save()
                messages.add_message(request, messages.SUCCESS,
                                     'Your profile has been updated')
                return redirect('accounts:profile')
            except Exception:
                account_form = AccountUpdateForm(request.POST,
                                                 instance=request.user)
                profile_form = ProfileFormUpdate(request.POST,
                                                 request.FILES,
                                                 instance=request.user.profile)
                context = {
                    'profile_form': profile_form,
                    'account_form': account_form,
                }
                return render(request, 'accounts/user-profile.html', context)
    context = {
        'account_form': account_form,
        'profile_form': profile_form
    }
    return render(request, 'accounts/user-profile.html', context)


@login_required(login_url="/accounts/login/")
def profile_delete(request):
    """
    This enables users to delete their profile
    """
    if request.method == 'POST':
        delete_form = DeleteUserForm(request.POST, instance=request.user)
        user = request.user
        user.delete()
        messages.add_message(request, messages.SUCCESS,
                             'Your profile has been deleted!')
        return redirect('accounts:signup')
    else:
        delete_form = DeleteUserForm(instance=request.user)
    context = {
        'delete_form': delete_form
    }
    return render(request, 'accounts/delete.html', context)

accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% load cloudinary %}
{% block content %}
<div class="height-controller">
<div class="form-container">
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <h1 class="delete-title">You are about to permanently delete your account!</h1>
        <p class="delete-content">Are you absolutely positive you want to delete your account?</p>
        {{ form }}
    </fieldset>
    <div class="form-group">
        <button class="delete-button" type="submit">Delete!!!</button>
        <a class="back-button" href="{% url 'accounts:user-profile' %}">Cancel</a>
    </div>
</form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/log-out.html
{% extends 'base.html' %}
{% load cloudinary %}
{% block content %}
<div class="height-controller">
    <div class="form-container">
        <h1>Log Out</h1>
        <p>Are you sure you want to log out?</p>
        <form method="post">
            {% csrf_token %}
            <input type="submit" class="mt-3 update-button" value="Log out">
            <a class="back-button" href="{% url 'reviews:review-display' %}">Back</a>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login-form.html
{% extends 'base.html' %}
{% load cloudinary %}
{% block content %}
<div class="height-controller">
    <div class="form-container">
        <h1>Log In</h1>
        <form class="login-inputs" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <input type="submit" class="mt-3 update-button" value="Login">
        </form>
        <p>Don't have an account?
            <br><br>
            <div class="center-button">
            <a class="back-button" href="{% url 'accounts:signup' %}">
                Register now!!
            </a>
        </div>
        </p>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load cloudinary %}
{% block content %}
<div class="height-controller">
    <div class="form-container">
        <h1>Register</h1>
        <div>
            <small>
                Have an account?
                <a class="back-button" href="{% url 'accounts:user-profile' %}">Sign In</a>
            </small>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="register-content">
                {{ form }}
            </div>
            <div class="center-button">
                <button class="back-button" type="submit">Sign up!!</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user-profile.html
{% extends 'base.html' %}
{% load cloudinary %}
{% block content %}
<div class="height-controller">
  <div class="form-container">

    {% if "default" in Profile.profile_image.url %}
    <img class="profile-image" src="{{ user.profile.profile_image.url }}" alt="placeholder image">
    {% else %}
    <img class="profile-image" src="{{ user.profile.profile_image.url }}" alt="Profile picture">
    {% endif %}
    <div class="media-body">
      <h2 class="account-title">{{ user.username }}</h2>
      <form method="POST" class="uniForm" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          {{ account_form }}
          {{ profile_form }}
        </div>
        <div class="profile-btns">
          <button class="update-button" type="submit">Update</button>
          <a class="back-button" href="{% url 'reviews:review-display' %}">Back</a>
          <a class="delete-button" href="{% url 'accounts:delete' %}">Delete</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}