accounts/urls.py
from . import views
from django.urls import path


app_name = 'accounts'


urlpatterns = [
    path('signups/', views.profile_register, name="signup"),
    path('login/', views.profile_login, name="login"),
    path('logout/', views.profile_logout, name="account_logout"),
    path('profile/', views.profile_view, name="user-profile"),
    path('profile/delete-account', views.profile_delete, name="delete"),
]

glassfish/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('', include('main.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('reviews.urls')),
]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='main'),
    path('gallery/', views.gallery, name='gallery'),
    path('visit/', views.visit, name='visit'),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'

urlpatterns = [
    path('reviews/', views.review_display, name='review-display'),
    path('reviews/<slug:slug>/', views.review_detail, name='reviews-detail'),
    path('create/', views.review_create, name='create'),
    path('<slug>/update/', views.review_update, name='update-review'),
    path('<slug>/delete/', views.review_delete, name='delete-review')
]

templates/base.html
{% load static %}

{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>GlassFish Aquarium</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link rel="apple-touch-icon" sizes="180x180"
        href="https://res.cloudinary.com/dgz5gpe5z/image/upload/v1708630039/apple-touch-icon_ifr0ns.png">
    <link rel="icon" type="image/png" sizes="32x32"
        href="https://res.cloudinary.com/dgz5gpe5z/image/upload/v1708630073/favicon-32x32_jiiyy8.png">
    <link rel="icon" type="image/png" sizes="16x16"
        href="https://res.cloudinary.com/dgz5gpe5z/image/upload/v1708630066/favicon-16x16_kfarrm.png">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <!-- This is the navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid navbar-border">
            <a class="navbar-brand homepage-title" href="#"><i class="fa-solid fa-fish-fins"></i> Glass Fish <i
                    class="fa-solid fa-fish-fins"></i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
                <ul>
                    {% if user.is_authenticated %}
                    <li class="nav-items">
                        <a href="{% url 'accounts:account_logout' %}">
                            Log out
                        </a>
                    </li>
                    <li class="nav-items">
                        <a href="{% url 'accounts:user-profile' %}">
                            Profile
                        </a>
                    </li>
                    <!-- profile icon where u can access ur profile -->
                    {% else %}
                    <li class="nav-items">
                        <a href="{% url 'accounts:login' %}">
                            Log in
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-items">
                        <a class="links" href="{% url 'main:gallery' %}">
                            Gallery
                        </a>
                    </li>
                    <li class="nav-items">
                        <a href="{% url 'main:visit' %}">
                            Visit
                        </a>
                    </li>
                    <li class="nav-items">
                        <a href="{% url 'reviews:review-display' %}">
                            Reviews
                        </a>
                    </li>
                    <li class="nav-items">
                        <a href="{% url 'main:main' %}">
                            Home
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- displaying Django messages -->
    <div class="container message-container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible
          fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- THIS IS WHERE ALL CONTENT IS RENDERED -->
    {% block content %}
    {% endblock %}

    <div class="footer-container">
        <!-- This  is the footer-->
        <footer>
            <ul>
                <!-- Footer items that direct you to a new page -->
                {% if user.is_authenticated %}
                <li class="footer-items">
                    <a href="{% url 'accounts:account_logout' %}">
                        Log out
                    </a>
                </li>
                <li class="footer-items">
                    <a href="{% url 'accounts:user-profile' %}">
                        Profile
                    </a>
                </li>
                {% else %}
                <li class="footer-items">
                    <a href="{% url 'accounts:login' %}">
                        Log in
                    </a>
                </li>
                {% endif %}
                <li class="footer-items display">
                    <a href="{% url 'main:gallery' %}">
                        Gallery
                    </a>
                </li>
                <li class="footer-items display">
                    <a href="{% url 'main:visit' %}">
                        Visit
                    </a>
                </li>
                <li class="footer-items display">
                    <a href="{% url 'reviews:review-display' %}">
                        Reviews
                    </a>
                </li>
                <li class="footer-items">
                    <a href="{% url 'main:main' %}">
                        Home
                    </a>
                </li>
            </ul>
        </footer>
    </div>
    <script src="https://kit.fontawesome.com/f302dda9d1.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js"></script>
</body>

</html>